### PR TITLE
New proposed main page

### PR DESCRIPTION
**Pull request by ivanzvonkov**
Look & feel + responsiveness

[Removed old demo video, new video linked below]

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
- [x] Add Harvest ML team

**Comment by ivanzvonkov** [comment]
https://user-images.githubusercontent.com/25067660/190196481-7c30253e-5a28-4459-a29e-bac39f7aab4e.mov

Updated to finish my parts of #4

**Comment by ivanzvonkov** [comment]
Added consistent header with ML logo and new main page description

@hannah-rae Let me know if the description is alright, also should other people be added to core team?

**Review by gabrieltseng — APPROVED** [review]
This looks great to me! I think this makes sense to merge in; we can iterate as necessary.

**Pull request merged**
